apiVersion: v1
kind: Service
metadata:
  name: hello-python-pdec-service
spec:
  selector:
    app: hello-python-pdec-v1.3
  ports:
  - protocol: "TCP"
    port: 5005
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python-pdec-v1.3
spec:
  selector:
    matchLabels:
      app: hello-python-pdec #precisa ser igual ao template/metadata/labels/app
  replicas: 4
  template:
    metadata:
      labels:
        app: hello-python-pdec
    spec:
      containers:
      - name: hello-python-pdec-ctn
        image: williamcardosoti/hello-python-pdec:1.3
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
